name: Build & Deploy

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - run: npm ci

      - run: npm run build

      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist


  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Test SFTP connectivity
        run: |
          echo "Testing TCP connection to $SFTP_HOST:$SFTP_PORT..."
          nc -vz $SFTP_HOST $SFTP_PORT || { echo "Host not reachable"; exit 1; }

      - name: Deploy via SFTP
        env:
          SFTP_HOST: ${{ secrets.HOST }}
          SFTP_PORT: ${{ secrets.PORT }}
          SFTP_USER: ${{ secrets.USER }}
          SFTP_KEY:  ${{ secrets.SSH_KEY }}
          SFTP_PATH: ${{ secrets.PATH }}
        run: |
          set -e
          echo "Checking connectivity to $SFTP_HOST:$SFTP_PORT..."
          nslookup "$SFTP_HOST" || { echo "Host not reachable"; exit 1; }

          echo "level 1"
          mkdir -p ~/.ssh
          echo "$SFTP_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H $SFTP_HOST >> ~/.ssh/known_hosts

          echo "level 2"
          lftp -u "$SFTP_USER" sftp://$SFTP_HOST:$SFTP_PORT  <<EOF
          set sftp:auto-confirm yes
          mirror -R --delete --verbose dist "$SFTP_PATH"
          EOF
